#!/bin/sh

set -o errexit

APP_VERSION="1.0.0"

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. make/include/colors.sh

printf "%b==> Building %b\n" "${OK_COLOR}" "${NO_COLOR}"

OSES="${OSES:-linux darwin windows}"
GOARCH=${GOARCH:-$(go env GOARCH)}

for OS in ${OSES}; do
  if [ "${OS}" == "windows" ]; then
    GOOS="${OS}" go build -ldflags="-X main.version=${APP_VERSION}" -o "build/${OS}-${GOARCH}/word_funnel.exe" 
 else
    GOOS="${OS}" go build -ldflags="-X main.version=${APP_VERSION}" -o "build/${OS}-${GOARCH}/word_funnel" 
  fi
done 

