#!/bin/sh

set -o errexit

. make/include/colors.sh

printf "%b==> Formatting%b\n" "${OK_COLOR}" "${ERROR_COLOR}"

ISSUES=$(mktemp)

trap "cat ${ISSUES} ; rm -f ${ISSUES}" EXIT

go fmt \
  $(go list -f ./...)  \
  >> "${ISSUES}"

printf "%b" "${NO_COLOR}"

test ! -s "${ISSUES}"
