#!/bin/sh

set -o errexit

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. make/include/colors.sh

printf "%b==> Vetting %b\n" "${OK_COLOR}" "${ERROR_COLOR}"

go vet $(go list ./... )

printf "%b" "${NO_COLOR}"
